viaMover/web-app

.eslintrc.js
src/assets/images/ios-spinner.svg
src/components/modals/savings-deposit-modal.vue
src/components/statements/progress-loader.vue
src/components/statements/statement-nav-list/statement-nav-list-item.vue
src/components/transaction-list/transaction-item.vue
src/main.ts
src/styles/_common.less
src/styles/_general.less
src/styles/_savings.less
src/styles/_treasury.less
src/wallet/actions/savings/deposit/depositSubsidized.ts
src/wallet/actions/savings/withdraw/withdrawSubsidized.ts
src/wallet/actions/subsidized.ts
src/wallet/actions/swap/swapSubsidized.ts
src/wallet/offchainExplorer.ts
src/web3/transaction.ts

+ subsidized txns fixes
+ pending txns
+ removed production logs
+ progress loader for savings\st

Subsidized txns fixes

---

src/components/modals/savings-deposit-modal.vue
src/components/modals/savings-withdraw-modal.vue
src/components/modals/swap-modal.vue
src/components/modals/treasury-claim-and-burn-modal.vue
src/components/modals/treasury-decrease-boost-modal.vue
src/components/modals/treasury-increase-boost-modal.vue
src/styles/_savings.less
src/styles/_treasury.less

Typo fix
Native decimals fix in modals

Small fixes

---

src/store/modules/account/actions/wallet.ts
src/web3/callbacks.ts

WC disconnect fix

---

src/router/wallet-auth-guard.ts
src/services/coingecko/tokens.ts
src/store/modules/account/actions/gas.ts
src/store/modules/account/actions/wallet.ts
src/wallet/ethPrice.ts

- add coingecko as eth price source
- add local storage cache for eth price
- increase gas update interval to 60s
- move gas listener start point

ETH price and gas fixes

---

src/store/modules/account/getters/wallet.ts
src/wallet/constants.ts

Cap sorting

---

src/store/modules/account/utils/charts.ts

What was done
* Added separate condition to check whether to trim current item or not
* Added a safeguard in case of 1 or more equal values are present in the source data
How to test
* Simulate the condition by substituting the result of `${baseUrl}/v1/savings/info/${address}` request with [this data](https://api.viamover.com/api/v1/savings/info/0xB0C7d0f6DFe3E786FE40214a4B99886FFC29F179)
<details>
<summary>mock data (extracted)</summary>
```javascript
const mockData = {
"status": "ok",
"payload": {
"currentBalance": 1071631,
"currentPoolBalance": 133347331276,
"earnedTotal": 4379,
"earnedThisMonth": 4380,
"last12MonthsBalances": [
{
"balance": 0,
"snapshotTimestamp": 1601510400,
"year": 2020,
"month": 9,
"earned": 0
},
{
"balance": 0,
"snapshotTimestamp": 1604188800,
"year": 2020, …
```

Charts: Fix filtering

---

src/views/nft/nft-view-moving-with-olympus.vue
src/views/nft/nft-view-sweet-and-sour.vue
src/views/nft/nft-view-unexpected-move.vue

Also added alternative sources if any (video/webm, video/mp4). Made a precedence with storage-hosted media then ipfs one

Assets: Use storage bucket-hosted media

---

src/views/nft/nft-view-moving-with-olympus.vue

UX: Add follow-up 'loadAvatar' action call to refresh state

---

src/store/modules/nft/actions/init.ts
src/styles/_shop.less
src/views/nft/nft-view-vaults.vue

What was done
* Removed vaults criteria fallback block
* Added feature-flagged vaults getter
How to test
* Not applicable

NFT: Feature/remove vaults criteria fallback block

---

src/services/mover/consts.ts
src/services/mover/savings/service.ts
src/services/mover/treasury/service.ts
src/services/zerion/transactions.ts
src/store/modules/account/actions/wallet.ts
src/store/modules/account/getters/wallet.ts
static_layouts/create-a-proposal.html
static_layouts/css/app.css
static_layouts/governance-overview.html
static_layouts/js/app.js
static_layouts/moving-with-olympus.html
static_layouts/savings-overview.html
static_layouts/smart-treasury-overview.html

Statistics endpoint change for savings and treasury

[FIX][TEMP] Statistics endpoint change

---

data/assetList.json
src/wallet/allTokens.ts
tools/token_list/index.js

What was done
* Added another way to obtain token data (through coingecko & ethplorer)
* Updated token list
Test plan
* Not applicable

[Feature] Update token list, token list generator

---

data/assetList.json
src/views/connect-wallet.vue
src/wallet/allTokens.ts
tools/token_list/index.js

What was done
* Added another way to obtain token data (through coingecko & ethplorer)
* Updated token list
Test plan
* Not applicable

[Intermediate release] Update token list

---

src/components/nft/nft-asset-card-mini/nft-asset-card-mini.vue
src/components/savings/savings-overview.vue
src/settings/globals.ts
src/styles/_shop.less

disable some savings-overview fields
disable nft-mini-card animation
fix dice popup background

Fixes (#104)

---

src/styles/_general.less

[FIX] Small design fix

---

data/assetList.json

**Context**
* Current project token list is outdated (~3 months since last update)
* New anticipated token `ENS` is available, probably our users will want to perform exchanges with it
**What was done**
* Updated tokens list

[Feature][Chore] Update tokens list

---

data/assetList.json

Context
* Current project token list is outdated (~3 months since last update)
* New anticipated token ENS is available, probably our users will want to perform exchanges with it
* Hotfix version of #162 
What was done
* Updated tokens list

[Hotfix][Feature][Chore] Update tokens list

---

src/components/savings/savings-withdraw-review.vue

fixed conditions for subs requests

[HOTFIX] Withdraw savings issue

---

src/views/savings/savings-withdraw-wrapper.vue

Changed NATIVE to TOKEN mode on savings withdraw page

[FIX] Savings withdraw token

---

src/i18n/messages/en.ts
src/store/modules/debit-card/types.ts
src/styles/_debit-card.less

Context
* The issues were found during the testing phase of the new feature
What was done
* Fixed debit card image background (black stripe under the image)
* Fixed invalid card status mapping
* Updated `Beautiful card` -> `Beautiful Card`

[Fix] Debit card issues

---

src/i18n/messages/en.ts
src/store/modules/debit-card/types.ts
src/styles/_debit-card.less

Context
* An intermediary release bringing recent fixes to the staging
Includes
* #173
* #174

[Feature] Intermediary staging release (Debit Card fixes)

---

src/i18n/messages/en.ts

Context
* Intermediary release bringing #176 to staging

[Fix] Debit card typo

---

src/components/debit-card/manage/debit-card-manage-change-phone.vue
src/components/debit-card/manage/debit-card-manage-order-card.vue
src/components/debit-card/manage/debit-card-manage-set-email.vue
src/components/debit-card/manage/debit-card-manage-validate-phone.vue
src/i18n/messages/en.ts
src/services/mover/debit-card/service.ts
src/store/modules/debit-card/actions.ts
src/styles/_debit-card.less

Context
* An email should be lowercased to prevent two entries from being created
* API responses need more granular handling
* Debit Card image is broken
* `ActionButton` in case of unmounted component is not reachable with `$refs`
* Phone number validator does not pass 10-digit number (apparently Norwegian use this format)
What was done
* Process email before hash creation, before order form data signature request
* Added Sentry breadcrumbs to the API errors
* Fixed width/height of Debit Card image
* Added safe checks to ActionButton
* Fixed boundaries of the phone number validator

[Fix] Debit Card first-day fixes

---

src/views/governance/governance-view-root.vue

Context
* A commented piece of code that doesn't work because of it
What was done:
* Uncommented navigation to the view-all

[Fix] Governance: Invalid proposal id

---

src/views/governance/governance-view-root.vue

Context
* An intermediary release bringing #180 to the staging

[Fix][Staging] Governance: Invalid proposal id

---

src/components/debit-card/manage/debit-card-manage-change-phone.vue
src/components/debit-card/manage/debit-card-manage-order-card.vue
src/components/debit-card/manage/debit-card-manage-set-email.vue
src/components/debit-card/manage/debit-card-manage-validate-phone.vue
src/i18n/messages/en.ts
src/services/etherscan/gas.ts
src/services/mover/debit-card/index.ts
src/services/mover/debit-card/service.ts
src/services/mover/debit-card/types.ts
src/services/mover/governance/service.ts
src/services/mover/responses.ts
src/services/responses.ts
src/services/zerion/transactions.ts
src/store/modules/debit-card/actions.ts
src/utils/emoji.ts
src/wallet/gas.ts

Context
* An intermediary release to the staging
Includes
* #186

[Release][Staging] Debit Card not supported country message

---

.circleci/config.yml
src/components/debit-card/manage/debit-card-manage-change-phone.vue
src/components/debit-card/manage/debit-card-manage-order-card.vue
src/components/debit-card/manage/debit-card-manage-set-email.vue
src/components/debit-card/manage/debit-card-manage-validate-phone.vue
src/i18n/messages/en.ts
src/services/etherscan/gas.ts
src/services/mover/debit-card/index.ts
src/services/mover/debit-card/service.ts
src/services/mover/debit-card/types.ts
src/services/mover/governance/service.ts
src/services/mover/responses.ts
src/services/responses.ts
src/services/zerion/transactions.ts
src/store/modules/debit-card/actions.ts
src/utils/emoji.ts
src/wallet/gas.ts

Context
* A release PR bringing recent fix/improvement regarding the not supported country error message
Included
* #187

[Release][Feature] Debit Card: Not supported country message

---

src/components/modals/search-modal/search-modal.vue
src/components/modals/swap-modal.vue

Prohibit to swap the same tokens

[FIX] Same token swap bug

---

src/i18n/messages/en.ts
src/services/chain/shop/tokens.ts
src/styles/_nibble.less

Context
* As smart contract address has been changed we need to update our local reference entry as well
What was done
* Changed an address of Cap NFT

[Fix] Update Cap address

---

src/i18n/messages/en.ts
src/views/debit-card/debit-card-top-up.vue

Added minimum amount for card top-up

[FEATURE] Minimum top-up amount

---

src/components/forms/review-form.vue
src/views/debit-card/debit-card-top-up.vue
src/views/earnings/olympus/earnings-olympus-stake.vue
src/views/earnings/olympus/earnings-olympus-withdraw.vue
src/views/savings/savings-deposit-wrapper.vue
src/views/savings/savings-withdraw-wrapper.vue
src/views/treasury/treasury-claim-and-burn-wrapper.vue
src/views/treasury/treasury-decrease-wrapper.vue
src/views/treasury/treasury-increase-wrapper.vue

Added functionality to pass formatted native balance to review component (use EUR for top up and native currency for the rest)
TODO/Notes:
* has a side-effect to #202

[FIX] Top up review eur

---

src/store/modules/debit-card/actions.ts

Context
* Intermediary release bringing recent debit card fixes to the staging
Includes
* #207

[Fix] Debit Card mapper

---

src/services/mover/debit-card/types.ts
src/store/modules/debit-card/actions.ts
src/store/modules/debit-card/types.ts

Context
* An intermediate release bringing mapper fix to the staging
Includes
* #209

[Fix] Debit card mapper (part 2)

---

src/components/forms/prepare-form/prepare-form.vue
src/components/treasury/treasury-left-rail.vue
src/i18n/messages/en.ts
src/router/index.ts
src/settings/globals.ts
src/styles/_common.less
src/views/savings/savings-deposit-wrapper.vue
src/views/savings/savings-withdraw-wrapper.vue
src/views/treasury/treasury-claim-and-burn-mobo-wrapper.vue
src/views/treasury/treasury-claim-and-burn-wrapper.vue
src/views/treasury/treasury-decrease-wrapper.vue
src/views/treasury/treasury-increase-wrapper.vue
src/wallet/actions/treasury/claimAndBurnMobo/claimAndBurnMobo.ts
src/wallet/actions/treasury/claimAndBurnMobo/claimAndBurnMoboEstimate.ts
src/wallet/references/abi/smart-treasury.json

* Claim And Burn MOBO: design and mock net func
add new section "claim & burn" with MOBO
add mock contract api function
add i18n texts for new section
fix claim & burn MOVE review page's texts
* Claim And Burn MOBO: Burn all
update component for burn all MOBO
* Claim And Burn MOBO: fixes after code-review
* Claim And Burn MOBO: fixes after code-review
* Claim And Burn MOBO: fixes after code-review
* added rounded mode for max label
* removed unnecessary logs
* Claim And Burn MOBO: update contract
* Claim And Burn MOBO: revert contract
Co-authored-by: Pavel <trukach000@gmail.com>

[FEATURE][Claim&Burn MOBO]: design and mock net func (#202)

---

src/i18n/messages/en.ts
src/services/chain/shop/tokens.ts

New nibble shop item -  OG shirt

[NIBBLE SHOP][NEW ITEM] OG shirt

---

src/services/chain/shop/tokens.ts
src/services/moralis/explorer.ts
src/wallet/references/data.ts
tools/token_list/data/assetList.json
tools/token_list/index.js

[FIX] Small fixes

---

data/assetList.json
src/wallet/references/data.ts
tools/token_list/index.js

Context
* New anticipated token is released (DOP -- Drops Ownership Power token)
What was done
* Added DOP token to the `alsoIncludedAddresses` list to manually include it to the search of complete active tokens list
* Added DOP token reference to the `data/references.ts`
* Added DOP token to the valid top up token list

[Chore] Add DOP token

---

data/assetList.json
src/wallet/references/data.ts
tools/token_list/index.js

Context
* An intermediary release bringing recent PRs to the staging
Includes
* #255

[Release][Chore] Add DOP token

---

src/services/chain/erc20/balance.ts
src/utils/bigmath.ts
src/views/debit-card/debit-card-top-up.vue
src/wallet/actions/debit-card/top-up/top-up-estimate.ts
src/wallet/actions/debit-card/top-up/top-up.ts
src/wallet/actions/debit-card/top-up/wxBTRFLY/estimate.ts
src/wallet/actions/debit-card/top-up/wxBTRFLY/top-up.ts
src/wallet/actions/types.ts
src/wallet/references/abi/wxbtrfly-abi.json
src/wallet/references/data.ts
src/wallet/types.ts
tools/token_list/index.js

Added wxBTRFLY as token for TopUP 
use unwrap mechanism to get BTRFLY token

[FEATURE] Add wxBTRFLY token for TopUP

---

src/views/debit-card/debit-card-top-up.vue

Context
* Missing fixes in different branches of the flow
What was done
* Added fixes to other branches

[Fix] wxBTRFLY flow (missing substitutions)

---

src/views/debit-card/debit-card-top-up.vue

* Fix: Add the same fix to other estimation methods (#238)

[Fix] wxBTRFLY fix for all routes

---

src/components/savings/savings-manage.vue
src/components/treasury/treasury-manage.vue
src/components/treasury/treasury-monthly-statement.vue
src/settings/persist/utils.ts
src/store/modules/savings/actions.ts
src/store/modules/savings/getters.ts
src/store/modules/savings/index.ts
src/store/modules/savings/mutations.ts
src/store/modules/savings/types.ts
src/store/modules/treasury/actions.ts
src/store/modules/treasury/getters.ts
src/store/modules/treasury/index.ts
src/store/modules/treasury/mutations.ts
src/store/modules/treasury/types.ts
src/views/savings/savings-global-analytics.vue
src/views/treasury/treasury-global-analytics.vue

fix persist store cache util
add cache to SavingsInfo
add cache to TreasuryInfo

[FEATURE] add cache to Treasury(Savings) Info

---

src/settings/globals.ts

- Enable back swap feature on home screen

[FLAG] Enable back swaps on home screen

---

src/services/coingecko/tokens.ts

[FIX] Multichain prices fix

---

src/views/nft/nft-view-order-of-liberty.vue

[FIX] Links fix

---

src/i18n/messages/en.ts
src/views/savings/savings-monthly-statistics.vue
src/views/treasury/treasury-monthly-statistics.vue

Context
* An intermediary release bringing recent fixes to the staging environment
Includes
* #276
* #277

[Release] Fixes propagation

---

src/components/controls/slippage-selector.vue
src/components/modals/swap-modal.vue
src/views/debit-card/debit-card-top-up.vue
src/views/earnings/olympus/earnings-olympus-stake.vue
src/views/savings/savings-deposit-wrapper.vue
src/wallet/actions/debit-card/top-up/top-up.ts

[FIX] Slippage change

---

src/components/modals/swap-modal.vue
src/services/coingecko/mapper.ts
src/services/coingecko/tokens.ts
src/services/moralis/explorer.ts
src/wallet/references/data.ts

Fixed prices for multichain txns and swap modal

[FIX] Multichain swap prices

---

src/components/modals/swap-modal.vue
src/services/coingecko/mapper.ts
src/services/coingecko/tokens.ts
src/services/moralis/explorer.ts
src/wallet/references/data.ts

Context
* An intermediary release bringing recent fixes & additions to the staging
Includes
* #291

[Release][Fix] Multichain swap prices

---

src/components/staking-ubt/staking-ubt-empty.vue

- Small fix to not display some fixed APY when zero UBT staked;

Change APY to 0 (for now) for UBT staking when zero UBT staked

---

src/views/staking-ubt/staking-ubt-withdraw-wrapper.vue

[FIX] UBT withdraw amount fix

---

src/components/staking-ubt/staking-ubt-empty.vue
src/views/staking-ubt/staking-ubt-withdraw-wrapper.vue

[FIX] Fixed UBT withdraw 

---

src/views/staking-ubt/staking-ubt-deposit-wrapper.vue

removed empty amount allowance from ubt deposit

[FIX] UBT deposit form small fix

---

src/views/staking-ubt/staking-ubt-deposit-wrapper.vue
src/views/staking-ubt/staking-ubt-withdraw-wrapper.vue

removed empty amount allowance from ubt deposit

[FIX] UBT deposit small fix

---

.circleci/config.yml
.env.development
.env.production
.env.stage
package.json
src/main.ts
src/services/v2/utils/sentry.ts
src/settings/globals.ts

Added stage environment variables;
It allows us to turn on the console logs on staging;

[FEATURE] Stage environment variables (Logs)

---

src/services/moralis/explorer.ts

[FIX] Fixed tokens prices

---

src/components/modals/swap-modal.vue
src/main.ts
src/services/coingecko/tokens.ts
src/services/explorer.ts
src/services/moralis/explorer.ts
src/services/moralis/types.ts
src/services/v2/api/APIService.ts
src/services/v2/api/coinGecko/CoinGeckoAPIService.ts
src/services/v2/api/coinGecko/index.ts
src/services/v2/api/coinGecko/types.ts
src/services/v2/api/index.ts
src/services/v2/api/theGraph/CurrencyNotSupportedError.ts
src/services/v2/api/theGraph/TheGraphAPIService.ts
src/services/v2/api/theGraph/index.ts
src/services/v2/api/theGraph/types.ts
src/services/v2/utils/price.ts
src/services/zerion/explorer.ts
src/settings/persist/utils.ts
src/shims-vue.d.ts
src/store/modules/account/actions.ts
src/store/modules/account/getters.ts
src/store/modules/account/index.ts
src/store/modules/account/mutations.ts
src/store/modules/account/types.ts
src/store/modules/staking-ubt/actions.ts
src/store/modules/utils.ts
src/utils/arrays.ts
src/utils/native-currency-formatter-mixin.ts
src/utils/network-data-mixin.ts
src/wallet/references/data.ts

[RELEASE] Native price services

---

package.json
src/app.vue
src/store/modules/account/actions.ts
src/views/connect-wallet.vue
yarn.lock

Clear all coinbase (walletlink) related stuff from local storage in case of error

[FIX] Coinbase failed behavior fix

---

src/components/layout/secondary-page/secondary-page-header.vue
src/components/staking-ubt/staking-ubt-manage.vue
src/i18n/messages/en.ts
src/styles/views/_staking-ubt.less

Allow to users toggle balance to token or native

[UI] Small UBT staking  UI update

---

src/views/treasury/treasury-claim-and-burn-mobo-wrapper.vue

[FIX] MOBO claim

---

.gitignore
src/wallet/references/data.ts

[TOKEN] Add token LUSD

---

.circleci/config.yml

Right order for deployment job

[FIX] CI change for proper stage deployment 

---

src/components/forms/review-form.vue
src/i18n/messages/en.ts
src/styles/modules/_form.less
src/views/savings-plus/savings-plus-withdraw-wrapper.vue

Added warning label in case of high bridge fee (Savings+)

[FEATURE] Warning on tx review form in case of high bridge fee

---

src/wallet/references/data.ts

Removed dCult from available for Top Up token list

[FIX] Remove dCULT from Top Up token list

---

src/wallet/references/data.ts

Removed dCULT from Top Up token list (temporarily) (#359)

---

src/components/staking-ubt/index.ts
src/components/staking-ubt/staking-ubt-empty.vue
src/components/staking-ubt/staking-ubt-manage.vue
src/components/staking-ubt/staking-ubt-monthly-statement.vue
src/i18n/messages/en.ts
src/router/index.ts
src/services/v2/api/mover/staking-ubt/MoverAPIStakingUbtService.ts
src/services/v2/on-chain/mover/staking-ubt/StakingUbtOnChainService.ts
src/services/v2/on-chain/mover/staking-ubt/types.ts
src/store/modules/staking-ubt/actions.ts
src/store/modules/staking-ubt/getters.ts
src/store/modules/staking-ubt/index.ts
src/store/modules/staking-ubt/mutations.ts
src/store/modules/staking-ubt/types.ts
src/views/staking-ubt/staking-ubt-global-analytics.vue
src/views/staking-ubt/staking-ubt-monthly-statistics.vue
src/views/staking-ubt/staking-ubt-root.vue

Includes: 
[Feature] UBT staking statistics #362

[Release] UBT staking statistics 

---

src/components/staking-ubt/index.ts
src/components/staking-ubt/staking-ubt-empty.vue
src/components/staking-ubt/staking-ubt-manage.vue
src/components/staking-ubt/staking-ubt-monthly-statement.vue
src/i18n/messages/en.ts
src/router/index.ts
src/services/v2/api/mover/staking-ubt/MoverAPIStakingUbtService.ts
src/services/v2/on-chain/mover/staking-ubt/StakingUbtOnChainService.ts
src/services/v2/on-chain/mover/staking-ubt/types.ts
src/store/modules/staking-ubt/actions.ts
src/store/modules/staking-ubt/getters.ts
src/store/modules/staking-ubt/index.ts
src/store/modules/staking-ubt/mutations.ts
src/store/modules/staking-ubt/types.ts
src/views/staking-ubt/staking-ubt-global-analytics.vue
src/views/staking-ubt/staking-ubt-monthly-statistics.vue
src/views/staking-ubt/staking-ubt-root.vue
src/wallet/references/data.ts

Updated UBT statistics
Includes:
#362

[Release] UBT staking statistics

---

src/components/staking-ubt/staking-ubt-monthly-statement.vue

Fix decimals in UBT staking receipt

[FIX] UBT receipt data small fix

---

src/components/staking-ubt/staking-ubt-monthly-statement.vue

[Fix] UBT receipt data fix

---

src/views/home.vue

Banner 'order of liberty' component removed from main page

[Feature] Remove liberty banner from home page

---

src/i18n/messages/en.ts
src/services/v2/on-chain/mover/savings-plus/SavingsPlusOnChainService.ts
src/services/v2/on-chain/mover/savings-plus/types.ts
src/store/modules/savings-plus/actions.ts
src/views/staking-ubt/staking-ubt-deposit-wrapper.vue
src/views/staking-ubt/staking-ubt-root.vue
src/views/staking-ubt/staking-ubt-withdraw-wrapper.vue
src/wallet/references/abi/savings-plus-pool-abi.json
src/wallet/references/data.ts

Some UBT staking statistics fixes
Proper S+ balance from contract on polygon chain

[FIX] Fix UBT staking stats + S+ balance on polygon

---

src/components/savings/savings-manage.vue
src/services/v2/on-chain/mover/savings-plus/SavingsPlusOnChainService.ts
src/store/modules/savings-plus/actions.ts

Removed logic to get s+ balance from contract on Polygon
Small color fix

[Fix] Remove savings+ pool balance from contract

---

src/components/savings/savings-manage.vue
src/services/v2/on-chain/mover/savings-plus/SavingsPlusOnChainService.ts
src/store/modules/savings-plus/actions.ts

[FIX] Removed S+ balance from contract on Polygon

---

src/components/home/home-transactions-list/home-transactions-list.vue
src/services/explorer.ts
src/services/moralis/explorer.ts
src/services/moralis/responses.ts
src/services/moralis/types.ts

Added logic to work with request's cursor for Moralis API

[FIX] Moralis explorer update

---

.gitignore
package.json
src/components/home/home-navigation-section.vue
src/components/home/home-transactions-list/home-transactions-list.vue
src/services/explorer.ts
src/services/moralis/explorer.ts
src/services/v2/api/0x/ZeroXAPIService.ts
src/services/v2/api/0x/types.ts
src/services/v2/api/ankr/AnkrAPIService.ts
src/services/v2/api/ankr/index.ts
src/services/v2/api/ankr/types.ts
src/services/v2/http.ts
src/services/v2/index.ts
src/services/v2/on-chain/mover/savings-plus/SavingsPlusOnChainService.ts
src/store/modules/account/actions.ts

Added ANKR API service and use it in Moralis explorer instead of Moralis API itself.
Use empty key for ANKR API

[FEATURE] ANKR token list

---

src/i18n/messages/en.ts

Change twitter button text for $tags

[TEXT CHANGE] Change button text

---

.env.production
.env.stage
.github/workflows/stage.yml
public/index.html
vue.config.js

Context
* Meta tags are using relative path so images can not be resolved properly
What was done
* Populated .env files with `VUE_APP_PUBLIC_PATH` values
* Used `process.env.VUE_APP_PUBLIC_PATH` in webpack configuration
* Moved meta tag creation to the `html-webpack-plugin` configuration
* Removed inlined meta tags
* Rearranged `<head>` entries according to the minimal `html-webpack-plugin` requirements

[Fix] OG, Twitter meta tags

---

vue.config.js

Context
* it affects the whole routing so should be removed

[Hotfix] Remove publicPath config value

---

src/app.vue
src/i18n/messages/en.ts
src/services/v2/NetworkNotSupportedError.ts
src/store/modules/account/actions.ts
src/store/modules/account/mutations.ts
src/store/modules/account/types.ts
src/store/modules/tag/actions.ts
src/views/connect-wallet.vue

In case of unsupported chain id throw special error and show the message

[FIX] Added Unsupported Chain error

---

src/i18n/messages/en.ts

[FIX] Fixed tag twit message text 

---

src/main.ts

Includes  (#436) - sentry tunnel

[FEATURE] Sentry tunnel

---

src/views/savings-plus/savings-plus-deposit-wrapper.vue
src/views/savings/savings-deposit-wrapper.vue

Show proper estimation in case of USDC without amount

[FIX] Savings estimation UI fix
