viaMover/web-app

src/router/index.ts, src/settings/globals.ts, src/views/release-radar/release-radar-view-all.vue, src/views/savings/savings-root.vue, src/views/treasury/treasury-root.vue
What was done
* Added a custom implementation of `router.back()` method
* Fixed invalid back button behavior (should not lead to the dashboard/home page always)
* Added a feature flag
How to test
* Enable `isNavigationFallbackAvailable` feature flag
* Make sure the provider is connected before following
* Visit `localhost:3000/savings` or `localhost:3000/treasury` from `page:blank` (important, to avoid previous navigation history)
* Click on 'back' navigation button
* Should be redirected to the `localhost:3000/` instead of `page:blank`
=> Fix: Add programmatic navigation fallback

src/settings/globals.ts
We've got a feature request from our users so here it is: navigation fallback preventing 'back' button from navigating all the way to the `page:blank`
=> UX: Enable navigation fallback

src/settings/persist/avatar.ts
What was done:
* Added an additional condition to check whether `addressBoundItem` is `undefined`
How to test:
* Not applicable
=> [FIX[ Avatar `.type` of `undefined`

src/components/home/menu-list/menu-list-emoji-card-item.vue, src/components/html5/custom-picture.vue, src/components/modals/details-picture.vue, src/components/modals/eth-picture.vue, src/components/modals/flip-picture.vue, src/components/modals/move-picture.vue, src/components/modals/savings-deposit-modal.vue, src/components/modals/savings-withdraw-modal.vue, src/components/modals/search-modal/search-modal-token-item.vue, src/components/modals/swap-modal.vue, src/components/modals/treasury-claim-and-burn-modal.vue, src/components/modals/treasury-decrease-boost-modal.vue, src/components/modals/treasury-increase-boost-modal.vue, src/components/modals/usdc-picture.vue, src/components/sections/section-base/section-base-link.vue
What was done
* Updated `<custom-picture>` component to pass styles (primarily for shadowing effect)
* Added new components to be reused (eth, move, usdc, details, flip icons)
* Updated components using `<picture>` to use `<custom-picture>` or it's derivatives
How to test
* Perform a brief check over each component that is changed, ensure nothing's broken
=> Chore: Use custom html5 picture

src/i18n/messages/en.ts, src/services/mover/governance/client.ts, src/store/modules/governance/actions.ts
Context
* Users were able to vote twice/more (depending on scenario and on what step they got an exceptional state)
* Although double voting is technically possible, it does not change anything really as only first vote counts
* If the command request takes `~5mins` to reach the server (**which is an exceptional situation by itself but definitely possible** by not confirming a message sign for long enough / bad internet connection), it always fails
What was done
* Added boundary checks for vote function (to prevent voting for/against inactive (pending / closed) proposals on the client side (to fail fast on early step and not make a request to the server each time))
* Add force update scenario: if a proposal is not closed but should be (proposal.end < now), the action will forcefully …
=> [Fix] Governance: Prevent double voting

src/components/modals/search-modal/search-modal-token-item.vue
Context
* This component is actually one of the most time-consuming ones
* Because of that, no unneeded actions should be here
What was done
* Removed console.log from `search-modal-token-item.vue`
=> [Fix] Remove time-consuming console.log

src/components/controls/dynamic-input.vue
Context
* During `<dynamic-input>`  `mounted()` lifecycle hook in case of non-empty value the width of input is calculated wrong
* It should have a width of value passed through the `props` but it is computed as `0.00`'s length
What was done
* Implemented prop-dependent input width calculation
=> [Fix] Dynamic input initial width

src/i18n/messages/en.ts
Context
* `our` -> `your`
What was done
* Fixed the typo
=> [Fix] Wrong timestamp error text typo

src/components/treasury/treasury-powercard-empty.vue, src/components/treasury/treasury-powercard-manage.vue, src/store/modules/account/actions/gas.ts, src/store/modules/account/actions/wallet.ts, src/store/modules/account/index.ts, src/store/modules/account/mutations/wallet.ts, src/store/modules/account/types.ts, src/store/modules/modals/actions.ts, src/store/modules/modals/index.ts, src/store/modules/modals/types.ts, src/utils/gas-listener-mixin.ts, src/views/savings/savings-deposit-wrapper.vue, src/views/savings/savings-withdraw-wrapper.vue, src/views/treasury/treasury-claim-and-burn-wrapper.vue, src/views/treasury/treasury-decrease-wrapper.vue, src/views/treasury/treasury-increase-wrapper.vue
**Context**
* Currently the gas listener runs on every view even if this is not necessary (this consumes API rates at about 4 requests/min)
**Approach explanation**
* Every view/component needing to listen to gas info is registered in a stack-like manner
* Once at least 1 listener is active, following listeners simply share the Vuex state. If no active listeners found then new gas listener loop is started
* Modals trigger start/stop on `setIsDisplayed(true/false)` events accordingly, considering the prototype flag `needGasListener`
* Views/other components use new `GasListenerMixin` to bind start/stop actions to their lifecycle hooks
* As the process should be wise about API quotes, an overrun logic is applied (similar to generator rotor overrun) -- the process still takes its place and …
=> [Feature] Gas listener on demand

src/components/sections/header-balance-section/header-balance.vue, src/i18n/messages/en.ts, src/router/index.ts, src/settings/globals.ts, src/store/index.ts, src/store/modules/nft/actions/init.ts, src/views/home-more.vue
Context
* An app contains unused feature flags which are unlikely to be toggled in the future
What was done
* Removed flags:
* isVaultsEnabled -- Vaults NFT
* isGovernanceEnabled -- Governance module (live & active)
* isNftDropsEnabled -- NFT Drops module (live & active, non-separable from current app state)
* isNavigationFallbackEnabled -- Navigation fallback preventing app from going to blank page after first render (live & active)
* isMoreEnabled -- More page (live & active, non-separable from current app state)
* Merged localizations where it was needed
=> [Chore] Cleanup feature-flags

src/i18n/messages/en.ts
Context
* All the `beautiful card` occurrences (case-independent) should be `Beautiful Card`
What was done
* Fixed text case
=> [Fix] Debit card typo

.circleci/config.yml
There is an issue https://github.com/getsentry/sentry-cli/issues/792
The fast way to solve it - add `--ignore-missing` flag
=> [FIX] Sentry release issue

.circleci/config.yml
Context
* Recently the deployment was interrupted by Sentry integration because of mixed git history
Includes
* #184
=> [Release][Staging] Sentry deployment fixes

src/components/debit-card/manage/debit-card-manage-change-phone.vue, src/components/debit-card/manage/debit-card-manage-order-card.vue, src/components/debit-card/manage/debit-card-manage-set-email.vue, src/components/debit-card/manage/debit-card-manage-validate-phone.vue, src/i18n/messages/en.ts, src/services/etherscan/gas.ts, src/services/mover/debit-card/index.ts, src/services/mover/debit-card/service.ts, src/services/mover/debit-card/types.ts, src/services/mover/governance/service.ts, src/services/mover/responses.ts, src/services/responses.ts, src/services/zerion/transactions.ts, src/store/modules/debit-card/actions.ts, src/utils/emoji.ts, src/wallet/gas.ts
Context
* Before this PR there was a case when not supported country and generic order API error were non-distinguishable
What was done
* Refactored generic data types to have optional typed payload
* Added special classes/types/cases for such errors
* Added new messages
* Refactored related code to use these data types as well
=> [Feature] Debit Card not supported country message

src/services/mover/debit-card/types.ts, src/store/modules/debit-card/types.ts
Context
* There is a new status on the API side (`CARD_ACTIVE`)
* The previous one was used in mapper -> inaccurate result of mapping
What was done
* Updated `ACTIVE` to `CARD_ACTIVE`
* Updated status mapper
* Fixed typo
=> [Fix] Card active status

src/store/modules/debit-card/actions.ts
Context
* The response payload occasionally contains the key with zero-valued entries
* The application code contains an implicit check of the final card status (CARD_ACTIVE)
What was done
* Replaced implicit check (`info.cardInfo !== undefined`) with an explicit one (`info.cardInfo?.cardStatus === 'CARD_ACTIVE'`)
=> [Fix] Debit Card mapper

src/services/mover/debit-card/types.ts, src/store/modules/debit-card/actions.ts, src/store/modules/debit-card/types.ts
Context
* `info.cardInfo.status` is used instead of `info.status`
* `ACTIVE` status (which is inner structure status) is missing from the type declaration
What was done
* Fixed the issue
=> [Fix] Debit card mapper (part 2)

src/settings/persist/utils.ts, src/store/modules/account/actions.ts, src/store/modules/savings/actions.ts, src/store/modules/treasury/actions.ts
Context
* All saved info should be bound to the current address
* Saved info will eventually pile up to the QUOTA_LIMIT and break storage
What was done
* Updated all usages of persist functions
* Added two cleaners
* removeExpiredPersistItemsFromLocalStorage
* removeAccountBoundPersistItemsFromLocalStorage
=> [Fix] Add address argument to persist functions

src/components/savings/savings-manage.vue, src/components/treasury/treasury-manage.vue, src/views/savings/savings-global-analytics.vue, src/views/treasury/treasury-global-analytics.vue
Context
* Because of lack of debounce/non-blocking loaders under Savings / Smart Treasury info loaders there is a possible case of looped action calls to the viaMover's view API
What was done
* Removed faulty action calls from Savings & Smart Treasury views
=> [Fix] Load action calls loop

src/components/home/home-cards/home-cards-order-of-liberty.vue
Context
* missing require causing invalid URL to appear in `<source>` tag
What was done
* Added `require()`
=> [Fix] Add missing require

src/i18n/messages/en.ts
Context
* Invalid error messages upon network change under some use-cases
What was done 
* Added missing `errors.default` translation key and value
=> [Fix] Invalid default error

src/views/savings/savings-monthly-statistics.vue, src/views/treasury/treasury-monthly-statistics.vue
Context
* Some of the values that are important to the render functions were evaluated as function presence instead of the function result value
What was done
* Moved invalid `is(.*)Enabled` functions to the "computed" section instead of "methods"
=> [Fix] Invalid component render states

src/services/explorer.ts, src/services/moralis/explorer.ts, src/store/modules/account/actions.ts
Context
* Currently the tokens on L2 networks are not displayed properly in search modal, transaction & wallet list
* Explorers send assets in lowercase format
* `isTokenListLoaded` is actually slowed down by transactions & native transactions query (contrary to what was intended)
What was done
* Added token info merging processor
* Added lowercase-to-checksum token address processor
* Moved process to trigger `isTokenListLoaded` ASAP
=> [Fix][Feature] Merge received explorer token info with local one

src/services/v2/on-chain/mover/savings/SavingsOnChainService.ts, src/services/v2/on-chain/mover/swap/SwapOnChainService.ts
Context
* Issue with base asset address in subsidized action string
* The API fails to parse `ETH` as an address
* Related:
* swap
* savings deposit
* send (not implemented yet included)
What was done
* Added base asset address substitution in subsidized actions
=> [Fix] Base asset address in subsidized actions

src/router/descending-meta-wrapper.ts, src/router/index.ts, src/store/types.ts
Context
* Previously it was possible to reach /debit-card/top-up/step/prepare route by direct link / manual address input
* This leads to successful transaction execution but if the state is invalid then card API doesn't know where to deposit assets
* Custom condition to guard such cases is required
What was done
* Added custom condition to check whether debit card state is valid or not
* Added the way to merge/ chain custom conditions (it is possible as they are predicates with the same signature) to each other by `appendMeta` helper function
=> [Fix] Guard top up route if state is invalid

src/services/v2/MoverError.ts, src/services/v2/api/mover/MoverAPIError.ts, src/services/v2/api/mover/MoverAPIService.ts, src/services/v2/api/mover/subsidized/MoverAPISubsidizedRequestError.ts, src/services/v2/api/theGraph/CurrencyNotSupportedError.ts, src/services/v2/api/theGraph/TheGraphAPIService.ts, src/services/v2/on-chain/OnChainServiceError.ts, src/services/v2/on-chain/mover/smart-treasury/SmartTreasuryOnChainService.ts, src/services/v2/on-chain/mover/staking-ubt/StakingUbtOnChainService.ts
Context
* Typically the `catch` section has `error` of type `unknown`. We almost certainly know that this argument is `instanceof Error`
* Code completion services throw warnings
* There might be a case where custom Object / primitive is thrown instead of Error-derivative
What was done
* Updated `wrap()` method to use `unknown` instead
* Also enforced the .payload type to Record<string, unknown> | undefined only
=> [Fix] Allow passing the `unknown` type to the wrap() method of MoverError

src/components/modals/swap-modal.vue, src/components/treasury/treasury-powercard-empty.vue, src/components/treasury/treasury-powercard-manage.vue, src/i18n/messages/en.ts, src/services/v2/on-chain/OnChainService.ts, src/services/v2/on-chain/mover/savings/SavingsOnChainService.ts, src/services/v2/on-chain/mover/smart-treasury/SmartTreasuryOnChainService.ts, src/services/v2/on-chain/mover/staking-ubt/StakingUbtOnChainService.ts, src/services/v2/on-chain/mover/swap/SwapOnChainService.ts, src/views/debit-card/debit-card-top-up.vue, src/views/savings/savings-deposit-wrapper.vue, src/views/savings/savings-withdraw-wrapper.vue, src/views/staking-ubt/staking-ubt-deposit-wrapper.vue, src/views/staking-ubt/staking-ubt-withdraw-wrapper.vue, src/views/treasury/treasury-claim-and-burn-mobo-wrapper.vue, src/views/treasury/treasury-claim-and-burn-wrapper.vue, src/views/treasury/treasury-decrease-wrapper.vue, src/views/treasury/treasury-increase-wrapper.vue, src/wallet/actions/actionWithApprove.ts, src/wallet/actions/debit-card/top-up/top-up-estimate.ts, src/wallet/actions/debit-card/top-up/top-up.ts, src/wallet/actions/debit-card/top-up/wxBTRFLY/estimate.ts
Context
* GasLimit too high / too low for a given transaction
* Opaque gas estimations
What was done
* Added ability to estimate tx again after successful approve tx
* Applied for each known use case (services)
* Updated estimation usages
TODO:
[ ] Resolve all TBD (see commit messages)
[x] debit-card-top-up actions -- apply the same fix / rewrite
[x] also patch executeTransactionWithApprove, executeTransactionWithApproveExt, OnChainService.executeTransactionWithApproveExt
=> [Fix] Estimate transaction gasLimit after approval

src/store/modules/nft/actions.ts
Context
* Some debug info was left
What was done
* Removed `console.debug` entries from `/store/modules/nft/actions.ts`
=> [Fix] Remove console debug entries from UNS/ENS code

src/app.vue, src/services/v2/utils/sentry.ts, src/store/modules/account/actions.ts, src/store/modules/nft/actions.ts, src/views/connect-wallet.vue
Context
* Utility function was missing the `warning` level so entries were never shown unless viewed in the Sentry
* Local development was missing the `warning` level logs
What was done
* Added `warning` level to the utility
=> Fix: Add `warning` Sentry level

src/main.ts
Added sentry tunnel via our endpoint to avoid blocking by Adblock-like apps
=> [FEATURE] Sentry tunnel
